mybook/api/urls.py
from django.conf.urls import url
from api import views

urlpatterns = [
    # 書籍
    url(r'^v1/books/$', views.book_list, name='book_list'),     # 一覧
]

mybook/cms/urls.py
from django.conf.urls import url
from cms import views

urlpatterns = [
    # 書籍
    url(r'^book/$', views.book_list, name='book_list'),   # 一覧
    url(r'^book/add/$', views.book_edit, name='book_add'),  # 登録
    url(r'^book/mod/(?P<book_id>\d+)/$', views.book_edit, name='book_mod'),  # 修正
    url(r'^book/del/(?P<book_id>\d+)/$', views.book_del, name='book_del'),   # 削除
    # 感想
    url(r'^impression/(?P<book_id>\d+)/$', views.ImpressionList.as_view(), name='impression_list'),  # 一覧
    url(r'^impression/add/(?P<book_id>\d+)/$', views.impression_edit, name='impression_add'),        # 登録
    url(r'^impression/mod/(?P<book_id>\d+)/(?P<impression_id>\d+)/$', views.impression_edit, name='impression_mod'),  # 修正
    url(r'^impression/del/(?P<book_id>\d+)/(?P<impression_id>\d+)/$', views.impression_del, name='impression_del'),   # 削除
]

mybook/mybook/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from django.conf.urls import url, include   # ←, includeを追加
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^cms/', include('cms.urls', namespace='cms')),
    url(r'^api/', include('api.urls', namespace='api')),  # ここを追加
]

mybook/api/models.py
from django.db import models

# Create your models here.

mybook/cms/models.py
# Create your models here.
from django.db import models


class Book(models.Model):
    """売上"""
    comike = models.CharField('コミックマーケット', max_length=255)
    title = models.CharField('同人誌タイトル', max_length=255, blank=True)
    price = models.IntegerField('単価', blank=True, default=0)
    cost = models.IntegerField('原価', blank=True, default=0)
    stock = models.IntegerField('冊数', blank=True, default=0)
    sell = models.IntegerField('売上冊数', blank=True, default=0)

    def __str__(self):
        return self.comike


class Impression(models.Model):
    """感想"""
    book = models.ForeignKey(Book, verbose_name='書籍', related_name='impressions')
    comment = models.TextField('コメント', blank=True)

    def __str__(self):
        return self.comment

mybook/cms/forms.py
from django.forms import ModelForm
from cms.models import Book, Impression

class BookForm(ModelForm):
    """書籍のフォーム"""
    class Meta:
        model = Book
        fields = ('comike', 'title','price', 'cost', 'stock', 'sell', 'stock', )


class ImpressionForm(ModelForm):
    """感想のフォーム"""
    class Meta:
        model = Impression
        fields = ('comment', )

mybook/api/views.py
import json
from collections import OrderedDict
from django.http import HttpResponse
from cms.models import Book


def render_json_response(request, data, status=None):
    """response を JSON で返却"""
    json_str = json.dumps(data, ensure_ascii=False, indent=2)
    callback = request.GET.get('callback')
    if not callback:
        callback = request.POST.get('callback')  # POSTでJSONPの場合
    if callback:
        json_str = "%s(%s)" % (callback, json_str)
        response = HttpResponse(json_str, content_type='application/javascript; charset=UTF-8', status=status)
    else:
        response = HttpResponse(json_str, content_type='application/json; charset=UTF-8', status=status)
    return response


def book_list(request):
    """書籍と感想のJSONを返す"""
    books = []
    for book in Book.objects.all().order_by('id'):

        impressions = []
        for impression in book.impressions.order_by('id'):
            impression_dict = OrderedDict([
                ('id', impression.id),
                ('comment', impression.comment),
            ])
            impressions.append(impression_dict)

        book_dict = OrderedDict([
            ('id', book.id),
            ('name', book.name),
            ('publisher', book.publisher),
            ('page', book.page),
            ('impressions', impressions)
        ])
        books.append(book_dict)

    data = OrderedDict([ ('books', books) ])
    return render_json_response(request, data)

mybook/cms/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic.list import ListView
from django.http import HttpResponse

from cms.models import Book, Impression
from cms.forms import BookForm, ImpressionForm

def book_list(request):
    """書籍の一覧"""
    #    return HttpResponse('売上一覧')
    books = Book.objects.all().order_by('id')
    return render(request,
                  'cms/book_list.html',  # 使用するテンプレート
                  {'books': books})  # テンプレートに渡すデータ


def book_edit(request, book_id=None):
    """書籍の編集"""
#     return HttpResponse('売上の編集')
    if book_id:   # book_id が指定されている (修正時)
        book = get_object_or_404(Book, pk=book_id)
    else:         # book_id が指定されていない (追加時)
        book = Book()

    if request.method == 'POST':
        form = BookForm(request.POST, instance=book)  # POST された request データからフォームを作成
        if form.is_valid():    # フォームのバリデーション
            book = form.save(commit=False)
            book.save()
            return redirect('cms:book_list')
    else:    # GET の時
        form = BookForm(instance=book)  # book インスタンスからフォームを作成

    return render(request, 'cms/book_edit.html', dict(form=form, book_id=book_id))

def book_del(request, book_id):
    """書籍の削除"""
    #     return HttpResponse('売上の削除')
    book = get_object_or_404(Book, pk=book_id)
    book.delete()
    return redirect('cms:book_list')

class ImpressionList(ListView):
    """感想の一覧"""
    context_object_name='impressions'
    template_name='cms/impression_list.html'
    paginate_by = 2  # １ページは最大2件ずつでページングする

    def get(self, request, *args, **kwargs):
        book = get_object_or_404(Book, pk=kwargs['book_id'])  # 親の書籍を読む
        impressions = book.impressions.all().order_by('id')   # 書籍の子供の、感想を読む
        self.object_list = impressions

        context = self.get_context_data(object_list=self.object_list, book=book)
        return self.render_to_response(context)

def impression_edit(request, book_id, impression_id=None):
    """感想の編集"""
    book = get_object_or_404(Book, pk=book_id)  # 親の書籍を読む
    if impression_id:   # impression_id が指定されている (修正時)
        impression = get_object_or_404(Impression, pk=impression_id)
    else:               # impression_id が指定されていない (追加時)
        impression = Impression()

    if request.method == 'POST':
        form = ImpressionForm(request.POST, instance=impression)  # POST された request データからフォームを作成
        if form.is_valid():    # フォームのバリデーション
            impression = form.save(commit=False)
            impression.book = book  # この感想の、親の書籍をセット
            impression.save()
            return redirect('cms:impression_list', book_id=book_id)
    else:    # GET の時
        form = ImpressionForm(instance=impression)  # impression インスタンスからフォームを作成

    return render(request,
                  'cms/impression_edit.html',
                  dict(form=form, book_id=book_id, impression_id=impression_id))

def impression_del(request, book_id, impression_id):
    """感想の削除"""
    impression = get_object_or_404(Impression, pk=impression_id)
    impression.delete()
    return redirect('cms:impression_list', book_id=book_id)

mybook/cms/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="{{ LANGUAGE_CODE|default:"en-us" }}">
<head>
<meta charset="UTF-8">
<title>{% block title %}My books{% endblock %}</title>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
<link href="{% static 'css/bootstrap-theme.min.css' %}" rel="stylesheet">
<script src="{% static 'js/jquery-2.2.0.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
{% block extrahead %}{% endblock %}
</head>
<body>
  <div class="container">
    {% block content %}
      {{ content }}
    {% endblock %}
  </div>
</body>
</html>

mybook/cms/templates/cms/book_edit.html
{% extends "base.html" %}
{% load bootstrap %}

{% block title %}売上の編集{% endblock title %}

{% block content %}
    <h3 class="page-header">売上の編集</h3>
    {% if book_id %}
    <form action="{% url 'cms:book_mod' book_id=book_id %}" method="post" class="form-horizontal" role="form">
    {% else %}
    <form action="{% url 'cms:book_add' %}" method="post" class="form-horizontal" role="form">
    {% endif %}
      {% csrf_token %}
      {{ form|bootstrap_horizontal }}
      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
          <button type="submit" class="btn btn-primary">送信</button>
        </div>
      </div>
    </form>
    <a href="{% url 'cms:book_list' %}" class="btn btn-default btn-sm">戻る</a>
{% endblock content %}

mybook/cms/templates/cms/book_list.html
{% extends "base.html" %}

{% block title %}売上の一覧{% endblock title %}

{% block extrahead %}
<style>
table {
  margin-top: 8px;
}
</style>
{% endblock %}

{% block content %}
    <h3 class="page-header">売上の一覧</h3>
    <a href="{% url 'cms:book_add' %}" class="btn btn-default btn-sm">追加</a>
    <table class="table table-striped table-bordered">
      <thead>
        <tr>
          <th>ID</th>
          <th>コミックマーケット</th>
          <th>同人誌タイトル</th>
          <th>売上金額</th>
          <th>在庫数</th>
          <th>操作</th>
        </tr>
      </thead>
      <tbody>
        {% for book in books %}
        <tr>
          <td>{{ book.id }}</td>
          <td>{{ book.comike }}</td>
          <td>{{ book.title }}</td>
          <td>{{ book.sell }}</td>
          <td>{{ book.stock }}</td>
          <td>
            <a href="{% url 'cms:book_mod' book_id=book.id %}" class="btn btn-default btn-sm">修正</a>
            <a href="{% url 'cms:book_del' book_id=book.id %}" class="btn btn-default btn-sm">削除</a>
            <!-- <a href="{% url 'cms:impression_list' book_id=book.id %}" class="btn btn-default btn-sm btn-primary">感想の一覧</a> -->
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
{% endblock content %}

mybook/cms/templates/cms/impression_edit.html
{% extends "base.html" %}
{% load bootstrap %}

{% block title %}感想の編集{% endblock title %}

{% block content %}
    <h3 class="page-header">感想の編集</h3>
    {% if impression_id %}
    <form action="{% url 'cms:impression_mod' book_id=book_id impression_id=impression_id %}" method="post" class="form-horizontal" role="form">
    {% else %}
    <form action="{% url 'cms:impression_add' book_id=book_id %}" method="post" class="form-horizontal" role="form">
    {% endif %}
      {% csrf_token %}
      {{ form|bootstrap_horizontal }}
      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
          <button type="submit" class="btn btn-primary">送信</button>
        </div>
      </div>
    </form>
    <a href="{% url 'cms:impression_list' book_id=book_id %}" class="btn btn-default btn-sm">戻る</a>
{% endblock content %}

mybook/cms/templates/cms/impression_list.html
{% extends "base.html" %}

{% block title %}感想の一覧{% endblock title %}

{% block extrahead %}
<script>
$(function() {
  $('.del_confirm').on('click', function () {
     $("#del_pk").text($(this).attr("pk"));
     $('#del_url').attr('href', $(this).attr("url"));
  });
});
</script>
<style>
table {
  margin-top: 8px;
}
</style>
{% endblock %}

{% block content %}
    <h3 class="page-header">感想の一覧 <small>{{ book.name }}</small></h3>
    <a href="{% url 'cms:impression_add' book_id=book.id %}" class="btn btn-default btn-sm">追加</a>
    <table class="table table-striped table-bordered">
      <thead>
        <tr>
          <th>ID</th>
          <th>コメント</th>
          <th>操作</th>
        </tr>
      </thead>
      <tbody>
        {% for impression in impressions %}
        <tr>
          <td>{{ impression.id }}</td>
          <td>{{ impression.comment|linebreaksbr }}</td>
          <td>
            <a href="{% url 'cms:impression_mod' book_id=book.id impression_id=impression.id %}" class="btn btn-default btn-sm">修正</a>
            <button class="btn btn-default btn-sm del_confirm" data-toggle="modal" data-target="#deleteModal" pk="{{ impression.id }}" url="{% url 'cms:impression_del' book_id=book.id impression_id=impression.id %}">削除</button>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>

    {% if is_paginated %}
    <ul class="pagination">
      {% if page_obj.has_previous %}
        <li><a href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
      {% else %}
        <li class="disabled"><a href="#">&laquo;</a></li>
      {% endif %}
      {% for linkpage in page_obj.paginator.page_range %}
        {% ifequal linkpage page_obj.number %}
          <li  class="active"><a href="#">{{ linkpage }}</a></li>
        {% else %}
          <li><a href="?page={{ linkpage }}">{{ linkpage }}</a></li>
        {% endifequal %}
      {% endfor %}
      {% if page_obj.has_next %}
        <li><a href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
      {% else %}
        <li class="disabled"><a href="#">&raquo;</a></li>
      {% endif %}
    </ul>
    {% endif %}

    <div>
      <a href="{% url 'cms:book_list' %}" class="btn btn-default btn-sm">戻る</a>
    </div>

{# 削除を確認するモーダル ダイアログ #}
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="deleteModalLabel">確認</h4>
      </div>
      <div class="modal-body">
        <p>ID: <span id="del_pk"></span> を削除しますか？</p>
      </div>
      <div class="modal-footer">
        <a href="#" class="btn btn-primary" id="del_url">OK</a>
        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
      </div>
    </div>
  </div>
</div>
{% endblock content %}